name: Stylus

on:
  push:
    paths:
      - 'stylus/**'
      - '.github/workflows/stylus.yml'
  pull_request:
    paths:
      - 'stylus/**'
      - '.github/workflows/stylus.yml'

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: stylus

    steps:
      - uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          override: true

      - name: Add wasm32 target
        run: rustup target add wasm32-unknown-unknown

      - name: Install cargo-stylus
        run: cargo install cargo-stylus

      - name: Run tests
        run: cargo test